# Form implementation generated from reading ui file '../ui/qt_render.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(813, 607)
        MainWindow.setStyleSheet("background-color: rgb(34, 37, 43);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(120, -10, 681, 611))
        self.frame.setStyleSheet("background-color: rgb(41, 44, 51);")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 681, 611))
        self.stackedWidget.setStyleSheet("QFrame{\n"
"background-color: rgb(44, 49, 58);\n"
"border: none;\n"
"}")
        self.stackedWidget.setObjectName("stackedWidget")
        self.create_program_page = QtWidgets.QWidget()
        self.create_program_page.setObjectName("create_program_page")
        self.label = QtWidgets.QLabel(parent=self.create_program_page)
        self.label.setGeometry(QtCore.QRect(200, 30, 251, 16))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(parent=self.create_program_page)
        self.frame_2.setGeometry(QtCore.QRect(10, 70, 421, 471))
        self.frame_2.setStyleSheet("background-color: rgb(45, 49, 57);\n"
"border: none;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 421, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
"<ui version=\"4.0\">\n"
" <widget name=\"__qt_fake_top_level\">\n"
"  <widget class=\"QLabel\" name=\"label\">\n"
"   <property name=\"geometry\">\n"
"    <rect>\n"
"     <x>200</x>\n"
"     <y>30</y>\n"
"     <width>251</width>\n"
"     <height>16</height>\n"
"    </rect>\n"
"   </property>\n"
"   <property name=\"font\">\n"
"    <font>\n"
"     <family>Helvetica</family>\n"
"     <pointsize>15</pointsize>\n"
"    </font>\n"
"   </property>\n"
"   <property name=\"text\">\n"
"    <string>РЕЖИМ СОЗДАНИЯ ПРОГРАММЫ</string>\n"
"   </property>\n"
"  </widget>\n"
" </widget>\n"
" <resources/>\n"
"</ui>\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalScrollBar = QtWidgets.QScrollBar(parent=self.frame_2)
        self.verticalScrollBar.setGeometry(QtCore.QRect(400, 0, 20, 471))
        self.verticalScrollBar.setStyleSheet("QScrollBar:vertical{\n"
"    background-color: rgb(181, 149, 243);\n"
"    width: 15px;\n"
"}\n"
"\n"
"QScrollBar:handle:vertical{\n"
"    background-color: rgb(40, 41, 64);\n"
"    min-height: 50px;\n"
"    border: 1px solid;\n"
"    border-color: rgb(254, 254, 254);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"height: 0px;\n"
"}\n"
"")
        self.verticalScrollBar.setMinimum(10)
        self.verticalScrollBar.setProperty("value", 50)
        self.verticalScrollBar.setTracking(True)
        self.verticalScrollBar.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.verticalScrollBar.setObjectName("verticalScrollBar")
        self.listWidget = QtWidgets.QListWidget(parent=self.frame_2)
        self.listWidget.setGeometry(QtCore.QRect(10, 40, 411, 411))
        self.listWidget.setStyleSheet("QListWidget {padding: 10px;} \n"
"QListWidget::item { margin: 10px; }\n"
"")
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.DragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.DropAction.MoveAction)
        self.listWidget.setObjectName("listWidget")
        self.widget = QtWidgets.QWidget(parent=self.create_program_page)
        self.widget.setGeometry(QtCore.QRect(430, 70, 221, 471))
        self.widget.setStyleSheet("background-color: rgb(34, 37, 42)")
        self.widget.setObjectName("widget")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setGeometry(QtCore.QRect(10, 270, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.comands_count_label = QtWidgets.QLabel(parent=self.widget)
        self.comands_count_label.setGeometry(QtCore.QRect(10, 140, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.comands_count_label.setFont(font)
        self.comands_count_label.setText("")
        self.comands_count_label.setObjectName("comands_count_label")
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.widget)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.ExecutionTimeLabel = QtWidgets.QLabel(parent=self.widget)
        self.ExecutionTimeLabel.setGeometry(QtCore.QRect(10, 220, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ExecutionTimeLabel.setFont(font)
        self.ExecutionTimeLabel.setText("")
        self.ExecutionTimeLabel.setObjectName("ExecutionTimeLabel")
        self.CommandsCountLabel = QtWidgets.QLabel(parent=self.widget)
        self.CommandsCountLabel.setGeometry(QtCore.QRect(10, 300, 191, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.CommandsCountLabel.setFont(font)
        self.CommandsCountLabel.setText("")
        self.CommandsCountLabel.setObjectName("CommandsCountLabel")
        self.AddCommandBtn = QtWidgets.QPushButton(parent=self.widget)
        self.AddCommandBtn.setGeometry(QtCore.QRect(30, 410, 161, 41))
        self.AddCommandBtn.setStyleSheet("QPushButton{\n"
"background-color: rgba(182, 149, 243, 0.6);\n"
"border-color: rgb(182, 149, 243);\n"
"border-radius: 10px;\n"
"}")
        self.AddCommandBtn.setObjectName("AddCommandBtn")
        self.ProgramNameEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.ProgramNameEdit.setGeometry(QtCore.QRect(10, 50, 181, 31))
        self.ProgramNameEdit.setStyleSheet("QLineEdit{\n"
"background-color: rgba(37, 39, 61, 240);\n"
"border: 1px solid;\n"
"border-color: rgb(182, 149, 243);\n"
"}\n"
"\n"
"")
        self.ProgramNameEdit.setObjectName("ProgramNameEdit")
        self.ProgramVersionEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.ProgramVersionEdit.setGeometry(QtCore.QRect(10, 140, 181, 31))
        self.ProgramVersionEdit.setStyleSheet("QLineEdit{\n"
"background-color: rgba(37, 39, 61, 240);\n"
"border: 1px solid;\n"
"border-color: rgb(182, 149, 243);\n"
"}\n"
"\n"
"")
        self.ProgramVersionEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.ProgramVersionEdit.setObjectName("ProgramVersionEdit")
        self.widget_2 = QtWidgets.QWidget(parent=self.create_program_page)
        self.widget_2.setGeometry(QtCore.QRect(10, 550, 641, 61))
        self.widget_2.setStyleSheet("background-color: rgb(45, 49, 58);")
        self.widget_2.setObjectName("widget_2")
        self.SaveProgramBtn = QtWidgets.QPushButton(parent=self.widget_2)
        self.SaveProgramBtn.setGeometry(QtCore.QRect(490, 10, 141, 41))
        self.SaveProgramBtn.setStyleSheet("QPushButton{\n"
"background-color: rgb(182, 149, 243);\n"
"border-color: rgb(182, 149, 243);\n"
"border-radius: 10px;\n"
"}")
        self.SaveProgramBtn.setObjectName("SaveProgramBtn")
        self.LoadProgramBtn = QtWidgets.QPushButton(parent=self.widget_2)
        self.LoadProgramBtn.setGeometry(QtCore.QRect(340, 10, 141, 41))
        self.LoadProgramBtn.setStyleSheet("QPushButton{\n"
"background-color: rgb(40, 41, 65);\n"
"border-color: rgb(182, 149, 243);\n"
"border-radius: 10px;\n"
"padding-left: 10px;\n"
"}")
        self.LoadProgramBtn.setObjectName("LoadProgramBtn")
        self.UploudFileBtn = QtWidgets.QPushButton(parent=self.widget_2)
        self.UploudFileBtn.setGeometry(QtCore.QRect(270, 10, 51, 41))
        self.UploudFileBtn.setStyleSheet("QPushButton{\n"
"background-color: rgb(40, 41, 65);\n"
"border-color: rgb(182, 149, 243);\n"
"border-radius: 10px;\n"
"padding-left:11px;\n"
"\n"
"}")
        self.UploudFileBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../ui/icons/arrow-up-32.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.UploudFileBtn.setIcon(icon)
        self.UploudFileBtn.setCheckable(True)
        self.UploudFileBtn.setObjectName("UploudFileBtn")
        self.ProgramFileNameLabel = QtWidgets.QLabel(parent=self.widget_2)
        self.ProgramFileNameLabel.setGeometry(QtCore.QRect(20, 10, 261, 41))
        self.ProgramFileNameLabel.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"color:  rgb(0, 0, 0);\n"
"padding: 10px;\n"
"}")
        self.ProgramFileNameLabel.setText("")
        self.ProgramFileNameLabel.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.ProgramFileNameLabel.setObjectName("ProgramFileNameLabel")
        self.stackedWidget.addWidget(self.create_program_page)
        self.device_configuration_page = QtWidgets.QWidget()
        self.device_configuration_page.setObjectName("device_configuration_page")
        self.label_7 = QtWidgets.QLabel(parent=self.device_configuration_page)
        self.label_7.setGeometry(QtCore.QRect(200, 26, 271, 20))
        font = QtGui.QFont()
        font.setFamily("Helvetica")
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.frame_3 = QtWidgets.QFrame(parent=self.device_configuration_page)
        self.frame_3.setGeometry(QtCore.QRect(10, 60, 641, 471))
        self.frame_3.setStyleSheet("QFrame\n"
"{\n"
"background-color: rgb(44, 49, 58);\n"
"border: none;\n"
"\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.textBrowser = QtWidgets.QTextBrowser(parent=self.frame_3)
        self.textBrowser.setGeometry(QtCore.QRect(5, 321, 631, 141))
        self.textBrowser.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.textBrowser.setObjectName("textBrowser")
        self.label_13 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_13.setGeometry(QtCore.QRect(20, 180, 141, 20))
        self.label_13.setObjectName("label_13")
        self.LoadFromDeviceBtn = QtWidgets.QPushButton(parent=self.frame_3)
        self.LoadFromDeviceBtn.setGeometry(QtCore.QRect(70, 230, 91, 31))
        self.LoadFromDeviceBtn.setStyleSheet("QPushButton{\n"
"background-color: rgb(182, 149, 243);\n"
"border-color: rgb(182, 149, 243);\n"
"border-radius: 10px;\n"
"}")
        self.LoadFromDeviceBtn.setObjectName("LoadFromDeviceBtn")
        self.UploadToDeviceBtn = QtWidgets.QPushButton(parent=self.frame_3)
        self.UploadToDeviceBtn.setGeometry(QtCore.QRect(180, 230, 91, 31))
        self.UploadToDeviceBtn.setStyleSheet("QPushButton{\n"
"background-color: rgb(182, 149, 243);\n"
"border-color: rgb(182, 149, 243);\n"
"border-radius: 10px;\n"
"}")
        self.UploadToDeviceBtn.setObjectName("UploadToDeviceBtn")
        self.label_14 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_14.setGeometry(QtCore.QRect(20, 20, 131, 31))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_15.setGeometry(QtCore.QRect(350, 70, 91, 31))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_16.setGeometry(QtCore.QRect(350, 120, 31, 31))
        self.label_16.setObjectName("label_16")
        self.LoggerComboBox = QtWidgets.QComboBox(parent=self.frame_3)
        self.LoggerComboBox.setGeometry(QtCore.QRect(180, 180, 161, 22))
        self.LoggerComboBox.setStyleSheet("QComboBox{\n"
"background-color: rgb(38, 40, 60);\n"
"border: 1px solid;\n"
"border-color: rgb(182, 149, 244); \n"
"}")
        self.LoggerComboBox.setObjectName("LoggerComboBox")
        self.LoggerComboBox.addItem("")
        self.LoggerComboBox.addItem("")
        self.LoggerComboBox.addItem("")
        self.label_17 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_17.setGeometry(QtCore.QRect(350, 20, 31, 31))
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_18.setGeometry(QtCore.QRect(20, 70, 131, 31))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(parent=self.frame_3)
        self.label_19.setGeometry(QtCore.QRect(20, 120, 161, 31))
        self.label_19.setObjectName("label_19")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setGeometry(QtCore.QRect(410, 20, 221, 241))
        self.frame_4.setStyleSheet("QFrame{\n"
"background-color: rgb(40, 44, 50);\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_10 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_10.setGeometry(QtCore.QRect(0, -1, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_11.setGeometry(QtCore.QRect(10, 50, 121, 16))
        self.label_11.setObjectName("label_11")
        self.device_program_version = QtWidgets.QLabel(parent=self.frame_4)
        self.device_program_version.setGeometry(QtCore.QRect(140, 50, 71, 21))
        self.device_program_version.setText("")
        self.device_program_version.setObjectName("device_program_version")
        self.DeviceVersionLabel = QtWidgets.QLabel(parent=self.frame_4)
        self.DeviceVersionLabel.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.DeviceVersionLabel.setText("")
        self.DeviceVersionLabel.setObjectName("DeviceVersionLabel")
        self.CountOfStepsEdit = QtWidgets.QLineEdit(parent=self.frame_3)
        self.CountOfStepsEdit.setGeometry(QtCore.QRect(180, 20, 161, 31))
        self.CountOfStepsEdit.setStyleSheet("QLineEdit{\n"
"background-color: rgba(37, 39, 61, 240);\n"
"border: 1px solid;\n"
"border-color: rgb(182, 149, 243);\n"
"}\n"
"\n"
"")
        self.CountOfStepsEdit.setObjectName("CountOfStepsEdit")
        self.StepsDivisionEdit = QtWidgets.QLineEdit(parent=self.frame_3)
        self.StepsDivisionEdit.setGeometry(QtCore.QRect(180, 70, 161, 31))
        self.StepsDivisionEdit.setStyleSheet("QLineEdit{\n"
"background-color: rgba(37, 39, 61, 240);\n"
"border: 1px solid;\n"
"border-color: rgb(182, 149, 243);\n"
"}\n"
"\n"
"")
        self.StepsDivisionEdit.setObjectName("StepsDivisionEdit")
        self.MaxSpeedEdit = QtWidgets.QLineEdit(parent=self.frame_3)
        self.MaxSpeedEdit.setGeometry(QtCore.QRect(180, 120, 161, 31))
        self.MaxSpeedEdit.setStyleSheet("QLineEdit{\n"
"background-color: rgba(37, 39, 61, 240);\n"
"border: 1px solid;\n"
"border-color: rgb(182, 149, 243);\n"
"}\n"
"\n"
"")
        self.MaxSpeedEdit.setObjectName("MaxSpeedEdit")
        self.widget_3 = QtWidgets.QWidget(parent=self.device_configuration_page)
        self.widget_3.setGeometry(QtCore.QRect(10, 550, 641, 61))
        self.widget_3.setStyleSheet("background-color: rgb(45, 49, 58);")
        self.widget_3.setObjectName("widget_3")
        self.ConnectBtn = QtWidgets.QPushButton(parent=self.widget_3)
        self.ConnectBtn.setGeometry(QtCore.QRect(400, 10, 131, 41))
        self.ConnectBtn.setStyleSheet("QPushButton{\n"
"background-color: rgb(182, 149, 243);\n"
"border-color: rgb(182, 149, 243);\n"
"border-radius: 10px;\n"
"}")
        self.ConnectBtn.setObjectName("ConnectBtn")
        self.ConnectFileUpload = QtWidgets.QPushButton(parent=self.widget_3)
        self.ConnectFileUpload.setGeometry(QtCore.QRect(270, 10, 51, 41))
        self.ConnectFileUpload.setStyleSheet("QPushButton{\n"
"background-color: rgb(40, 41, 65);\n"
"border-color: rgb(182, 149, 243);\n"
"border-radius: 10px;\n"
"padding-left:11px;\n"
"\n"
"}")
        self.ConnectFileUpload.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../ui/icons/usb-2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ConnectFileUpload.setIcon(icon1)
        self.ConnectFileUpload.setIconSize(QtCore.QSize(32, 32))
        self.ConnectFileUpload.setCheckable(True)
        self.ConnectFileUpload.setObjectName("ConnectFileUpload")
        self.ConnectFileLabel = QtWidgets.QLabel(parent=self.widget_3)
        self.ConnectFileLabel.setGeometry(QtCore.QRect(20, 10, 261, 41))
        self.ConnectFileLabel.setStyleSheet("QLabel{\n"
"background-color: rgb(255, 255, 255);\n"
"color:  rgb(0, 0, 0);\n"
"padding: 10px;\n"
"}")
        self.ConnectFileLabel.setText("")
        self.ConnectFileLabel.setTextFormat(QtCore.Qt.TextFormat.MarkdownText)
        self.ConnectFileLabel.setObjectName("ConnectFileLabel")
        self.ProgressBar = QtWidgets.QProgressBar(parent=self.widget_3)
        self.ProgressBar.setGeometry(QtCore.QRect(550, 20, 71, 23))
        self.ProgressBar.setStyleSheet("QProgressBar\n"
"{\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk\n"
"{\n"
"    background-color:rgb(182, 149, 243);\n"
"}\n"
"")
        self.ProgressBar.setProperty("value", 24)
        self.ProgressBar.setObjectName("ProgressBar")
        self.DisconnectBtn = QtWidgets.QPushButton(parent=self.widget_3)
        self.DisconnectBtn.setGeometry(QtCore.QRect(400, 10, 131, 41))
        self.DisconnectBtn.setStyleSheet("QPushButton{\n"
"background-color: rgb(255, 144, 139);\n"
"border-color: rgb(255, 144, 139);\n"
"border-radius: 10px;\n"
"}")
        self.DisconnectBtn.setObjectName("DisconnectBtn")
        self.stackedWidget.addWidget(self.device_configuration_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.frame_5 = QtWidgets.QFrame(parent=self.settings_page)
        self.frame_5.setGeometry(QtCore.QRect(20, 20, 651, 581))
        self.frame_5.setStyleSheet("QFrame{\n"
"\n"
"\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_12 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_12.setGeometry(QtCore.QRect(10, 500, 131, 31))
        self.label_12.setObjectName("label_12")
        self.program_version_label_2 = QtWidgets.QLabel(parent=self.frame_5)
        self.program_version_label_2.setGeometry(QtCore.QRect(150, 500, 121, 31))
        self.program_version_label_2.setObjectName("program_version_label_2")
        self.label_21 = QtWidgets.QLabel(parent=self.frame_5)
        self.label_21.setGeometry(QtCore.QRect(10, 530, 181, 31))
        self.label_21.setObjectName("label_21")
        self.check_program_update_btn = QtWidgets.QPushButton(parent=self.frame_5)
        self.check_program_update_btn.setGeometry(QtCore.QRect(410, 510, 211, 41))
        self.check_program_update_btn.setStyleSheet("QPushButton{\n"
"background-color: rgb(40, 41, 65);\n"
"border-color: rgb(182, 149, 243);\n"
"border-radius: 10px;\n"
"padding-left: 10px;\n"
"}")
        self.check_program_update_btn.setObjectName("check_program_update_btn")
        self.stackedWidget.addWidget(self.settings_page)
        self.ProgramModeBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ProgramModeBtn.setGeometry(QtCore.QRect(20, 140, 81, 81))
        self.ProgramModeBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(182, 149, 243);\n"
"    border: 1px solid;\n"
"    border-radius: 20px;\n"
"}")
        self.ProgramModeBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../ui/icons/program-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ProgramModeBtn.setIcon(icon2)
        self.ProgramModeBtn.setIconSize(QtCore.QSize(60, 60))
        self.ProgramModeBtn.setObjectName("ProgramModeBtn")
        self.ControllerProgrammingBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ControllerProgrammingBtn.setGeometry(QtCore.QRect(20, 250, 81, 81))
        self.ControllerProgrammingBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(182, 149, 243, 0);\n"
"    border: 1px solid rgba(182, 149, 243, 0);\n"
"    border-radius: 20px;\n"
"}")
        self.ControllerProgrammingBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../ui/icons/processro-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ControllerProgrammingBtn.setIcon(icon3)
        self.ControllerProgrammingBtn.setIconSize(QtCore.QSize(60, 60))
        self.ControllerProgrammingBtn.setObjectName("ControllerProgrammingBtn")
        self.SettingsBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.SettingsBtn.setGeometry(QtCore.QRect(20, 360, 81, 81))
        self.SettingsBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgba(182, 149, 243, 0);\n"
"    border: 1px solid  rgba(182, 149, 243, 0);\n"
"    border-radius: 20px;\n"
"}")
        self.SettingsBtn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../ui/icons/settings-100.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.SettingsBtn.setIcon(icon4)
        self.SettingsBtn.setIconSize(QtCore.QSize(60, 60))
        self.SettingsBtn.setObjectName("SettingsBtn")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "РЕЖИМ СОЗДАНИЯ ПРОГРАММЫ"))
        self.label_2.setText(_translate("MainWindow", "ИСПОЛНЯЕМЫЕ КОМАНДЫ:"))
        self.label_3.setText(_translate("MainWindow", "Название файла: "))
        self.label_4.setText(_translate("MainWindow", "Количество комманд:"))
        self.label_5.setText(_translate("MainWindow", "Версия программы:"))
        self.label_6.setText(_translate("MainWindow", "Время выполнения:"))
        self.AddCommandBtn.setText(_translate("MainWindow", "Добавить команду"))
        self.SaveProgramBtn.setText(_translate("MainWindow", "СОХРАНИТЬ"))
        self.LoadProgramBtn.setText(_translate("MainWindow", "ЗАГРУЗИТЬ"))
        self.label_7.setText(_translate("MainWindow", "РЕЖИМ НАСТРОЙКИ УСТРОЙСТВА"))
        self.label_13.setText(_translate("MainWindow", "Уровень логирования"))
        self.LoadFromDeviceBtn.setText(_translate("MainWindow", "СЧИТАТЬ"))
        self.UploadToDeviceBtn.setText(_translate("MainWindow", "ЗАПИСАТЬ"))
        self.label_14.setText(_translate("MainWindow", "Кол-во шагов за мм"))
        self.label_16.setText(_translate("MainWindow", "мм."))
        self.LoggerComboBox.setItemText(0, _translate("MainWindow", "NO_LOG"))
        self.LoggerComboBox.setItemText(1, _translate("MainWindow", "INFO"))
        self.LoggerComboBox.setItemText(2, _translate("MainWindow", "DEBUG"))
        self.label_17.setText(_translate("MainWindow", "шаг."))
        self.label_18.setText(_translate("MainWindow", "Деление шага"))
        self.label_19.setText(_translate("MainWindow", "Максимальная скорость"))
        self.label_10.setText(_translate("MainWindow", "ИНФОРМАЦИЯ ОБ УСТРОЙСТВЕ:"))
        self.label_11.setText(_translate("MainWindow", "Версия прошивки:"))
        self.ConnectBtn.setText(_translate("MainWindow", "КОННЕКТ"))
        self.DisconnectBtn.setText(_translate("MainWindow", "ДИСКОННЕКТ"))
        self.label_12.setText(_translate("MainWindow", "Версия программы:"))
        self.program_version_label_2.setText(_translate("MainWindow", "0.0.1-alpha"))
        self.label_21.setText(_translate("MainWindow", "Developed by: Sinthetic-Ninja"))
        self.check_program_update_btn.setText(_translate("MainWindow", "ПРОВЕРИТЬ ОБНОВЛЕНИЕ"))
